{{- /*
Convert a size in Gi (e.g. "5Gi") to bytes.
*/ -}}
{{- $sizeStr := .Values.prometheus.persistenceLonghorn.size | trimSuffix "Gi" -}}
{{- $sizeGi := $sizeStr | int -}}
{{- $sizeBytes := mul $sizeGi (mul 1024 (mul 1024 1024)) -}}

apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: {{ .Values.prometheus.persistenceLonghorn.pvName | quote }}
  namespace: longhorn-system
spec:
  numberOfReplicas: {{ .Values.prometheus.persistenceLonghorn.numberOfReplicas }}
  frontend: {{ .Values.prometheus.persistenceLonghorn.frontend | quote }}
  backupTargetName: {{ .Values.prometheus.persistenceLonghorn.backupTargetName | quote }}
  size: "{{ $sizeBytes }}"
  {{- if .Values.prometheus.persistenceLonghorn.restore }}
  fromBackup: {{ .Values.prometheus.persistenceLonghorn.fromBackup | quote }}
  {{- end }}
