apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls
  namespace: demo
spec:
  secretName: whoami-tls  # ✅ Cert-Manager will create this Secret automatically
  issuerRef:
    name: ${CERT_ISSUER}  # This will be replaced by the script
    kind: ClusterIssuer
  dnsNames:
    - whoami.atlasmalt.com  # ✅ This must match the domain in your IngressRoute
