apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls
  namespace: demo
spec:
  secretName: whoami-tls  # ✅ Cert-Manager will create this Secret automatically
  issuerRef:
    name: letsencrypt-prod  # ✅ Matches your ClusterIssuer
    kind: ClusterIssuer
  dnsNames:
    - whoami.atlasmalt.com  # ✅ This must match the domain in your IngressRoute
