{{- if .Values.longhorn.ingressroute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: longhorn-system
  annotations:
    {{- range $key, $value := .Values.longhorn.ingressroute.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`{{ .Values.longhorn.ingressroute.host }}`)"
      kind: Rule
      middlewares:
        - name: longhorn-auth
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: {{ .Values.longhorn.ingressroute.tls.secretName }}
{{- end }}
