---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: cert-manager
spec:
  encryptedData:
    apiKey: AgAQhlJIimyTF+Ie6crkKdmI6ckbmMrSFLWOc9i+THTb1kK2HzfMUv12+LdtUKcyiagav37/Q3J7Uuba+HbRIN0Qpe+3hatlHTQtdGzj4khjvHJRyEO9pPwHKoebYMF8oww7CQ5wa0zYq3Fj89CsUhazT6y7yiVL+9LpNrFn8C5gvVkFDRuB4UEoQHyVkTQbZcHkmzV6R2Go+QMWX6I9/KdlhdAzfsN+Pd5U0Ogrz24p4Cy1oWzIjiAlwHsEg1g2G7j2wgT4gNfISA5+Z1PIDwpJNtlabQRGWGuGGncTfrX13VFsu3UbpkOkFY4NzfY8o3ryTk+JjMEQ2JchebqUihDBtX+iMU7UJ7dng/jW/83TOc090Myu6qdgbH7o/enWrOkXrUTrSQshHBseiwMqHlNWK3atrDCUhc/Y1Sx1wQGqTracAiRf7pmAhHr9dz1rl4M+dJ4qBDZSBGRuUZ3ZaqQbtojwiDR7Etk7LnYFJnkVP7YOUxgork2hLAcA6dQat0Ya/9aOkttrGdc6HIUIY+Z46hLRSGy48oMGX7iR5tpeqJSQBhjPr4tkCrO4ELqURqw9HUCLvCqX/np50ZbB1KUrpITeZrrmOOWMY8/WEIm/uH+rUy+DrSuchNysNxs2658x7uBFW/CrhcbJT05OTf83nI3wKR63hkEnHdnLh8D0AUeV6kRkvCYABUrkwal5ERCyTsqmXicAP3anIurXq+KrWrJ4wB8yKSJwJvWcQjd3hn3ULdN4BkRh
    email: AgBK5+Wm2LBAiPTIdZjvl7KR5iwZfI8svBGqu7uHpGGk/NIhWAAXDVuTcY7ZVyItZ0WqmQ6VBzVAYSPO7EWBGgMvbrxsHuaBjNgUM/dAsNKGIEYxzJQ4U6QLMH80mH3Ai6ceKvChEWsoupDC889OYUXfwFRFhKSsyyDMuOhwcwwExfIUaJr5sdVkENNPV4nqZkFBsiTYSnCp1n7bZwcnKlypgtJi1FgXYZwWATNd7jPGsOYYpw5q0k+siQrIWuwkmQr+dqKW5VebH1PxLJdx51eqMbhLDSdnuokpDeMvQmh57e47YXIY4lKt9J9+qzgLSsCqDOIcYtaxWu5UVDPAeJN3T5Y2rWq7zjaJRzXdlHWQVtIeZLAC/Y1Nkwf/l21Kim+buoDrCpAWqqOVXzFqRD7vjCAunf3mnv6reKZCVeATd/GU0NNvPX56gb4Ni1mPoLTcYBb8w4WRczm+hKjBsPKvRTddTCwsoSoDWIYkB73Ia6R8DyIgHWpCSB78D+Jl6EffIHl6Su7tMl/fxlMS5mVj3xDsj9IQeLqZPlKF17Htum3wxjuCEtbKuo0nocbjvTUP48gfquCldnk/FGviIsrzwJSC1A07K8Lt1l2Aytdv9CXRCpsuhD2TaA6b3gL4pCYgDGG9Pflw8OnkBUl7lK4vzDiPql0qeK2v5vGFJmq51Z0p4lSiO7D5yyrc9l403jdz+JcXdmye/b2uX4zOccgtVoORdQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: cert-manager
