---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-actions-token
  namespace: gitea
spec:
  encryptedData:
    token: AgAl/Fa4M4KOq0A2QEqs0AEUkoS/aijtKl+xXOUrIi5ukUMo1qWPGYnXXqgbYhBeIKaRZey896aaWa5nt2O7aheJdoVeW1zi31M0z5L1aTS9E8/btBKdITangVaqfm8prx8yNrWhj1ybeAW+6CzDPgjECc+/VZWKn5z5AqRmPoaRSc1BRt/Fi7PolzcX0K8cvb4q/XIkzeixqRDMPvxvT3dzySxYwSdzsDReEQQqFU2rdFKBIniZKUdo34prE7CqrBK8VBs7jmL4U1TLiwumLHB7oNJm8xUU3DG63WCsHNud/mH1J+ndI8qeje2nTSu1mg0zXbMuYqW4uqrWELERTrgoebx3Db7X49+LZKAk6tSjnOMmWelfQD525MZrVSgCrkv9LK/QjSzu7e96Onhomt3/UeE2mIXWWxwwZdX6EF8EFhiDGGGbIi15aMppJQYegYz1VGlBZGIVz10918Rve0MQPQb5T60QKOQX7OTJNRKIHbHt8yaVMktWLiaYxZ20PaDyDiEr66tdCYoWlQXBqUAWk6uza9zqi/hUCNz1xKYKmvQTBXo7h1DtbnmFMVQcDVUlBYIPyZmG1VqEbIECa0N4CMktdNkE4tpQBrVJTzazn2QXWiwvryKl0RsyWNuLyQg/sfL6+4eYxUbPG/cRdb0tZEJM3O0Lp4krvx/FIaHeHOI1tvL1TEf4ui6OLbiF3eeoopQlLwxNaD/gsHcTZbVFLK6W60S8LCFEKoClQr76o3nOUgZlFPiU
  template:
    metadata:
      creationTimestamp: null
      name: gitea-actions-token
      namespace: gitea
    type: Opaque
