---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAKn5Mn3I2V3/utTemMdT3gKNWDQKiMCLWANRpdkmQD6v9o3NOm3pSDDOdG8sxg4MTEiN6zYQilBU8b3pCUQY4ZDudqq9YXeudxBPvVAiZWwhQ3TZnQKR0ozbBjsNXvTeFS/uLvjvC8RLE3t6/RwiVLf/CveuaOxvPa3yH6xyvrSaV64IBfCmvESptfl0LlsswYDicQttEzgIgEZThiBoc6DwHhLMnCxmipRNVQqbBWiX3FrMZ5MWzQM40N+3GYnYjZqsJlLW/fxHce+MWhxU6hSXkFqoFd9OrJlujI2uEvMfYPwCj8tyTOJ1JBMC/f6+J9PnHdRoec7+KtItb84/WS01QGzxpb+ychH4mA7ggemDP8ZUgGAX2owd2yAfICjPi2et0bkFCwf17jjKnPvOhhTkFWSA4xAHSBiO/Je5b8oimO0fqenwtXVjJBYWtXrPQqX/L2aR/xWNKUCrr3veGJQK8w2H51vS8tBVWBtZmgrlhIgbPYwFBgAbukymbNVype/EPIqDYz8cEuggLefo8Z/6xB6I6Rj64ov4laZjZKde1NODR1rGdwnrGqDgZEVsQbf1U3jAe9GX6jmzwD7Bc/lsHO0ogDGjd18VG4T32sVNp0fV1NVTP5KYNKgbpRAeIT5778iZ2bJcdTjc7//UAm+ct8HAZ/75A5yGATLu2h5NauYMDOf56tYvSDWCiejKXOUNKaP48d/m92I7NrfLKvHts/CvQfNm3mp9B6HydUiDBhrkk=
    admin-user: AgBCThIR5BtGu+ifkZrG6w7Y5uBL6MNzcxmeKVmEqe2ygHYWOK5MStsI2p24B/HH5gsEZFx2z+Y/rfU9rNiRoXN8nRUwdxNe12VYhjMWJ9RrwgaQ/iodMEiyJdhAV5CtpltOfW5ToNB05hnYt9UUtJagV6dBDAvHbYxRRR37Kgpi9OzjHqnLpaRNRH7Bk5aZNMT/5litSr66yF0SmB6Q6gTlVekYQRy94aSwaLaV3+xiLlNDC0YvwqbVXcjA149hUYwIpkB6oswoo3su8UGPGFwNypDXL0GLi1kiL329haF8AKLxJV9knk2ZNrQPmsOFS3wz+ZdgeQ5QXZbmPDKrLWDRJaI3XlV/rSoLZOGlMNkEsKnL6hu3r79ccY7+/n+UWpmpbn0SZ+lxtdj5e+PmQoy6cV0pjJDMovp6IYX/Dv9pdVzCdmupo1kx24NrqFPk1fVZPPuWhzzzEKtFqfZO2w9ac4wyAZ7MAFUhp7/oaFeYH1i2KT1+zKvZz5CtpUiInphtkkrjP9kmo7/42gkVY47b+iCY6123dzReFSBHPTuSaNMisPyNZSXg/Zs7dD81MwWlnvgxvD8t/JnR8yZenWKhwClC5LMZLpAEafzYEr6QuW/WSqrex8Vsv+hiYx0VJniHyRWtsxgk/6Q8uf2CVjD7aTy21wix6prei8pxwCKWuKhTzrrzZdThobrPmrlVIySvFOmXog==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
