---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-auth
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgC2PNJs2eCUOdR2mu1j1ajvV2y2DBpcjem6bHMeTIPpJ2LZV7IiJu61PBpy0i00XBtgNIIaHUZLo7tvGhK0XM2tBUu831uWtxmaE3k/TntuT49XJbC7lNRtgy0//A/8jGiwG/1vyFtdfk8YBLXjn3yU/JMKw/RrNZt3+49O7MGZizZC6jg13nm9Y7KoWcdyjy9dz6MpvoIIvskfe954PGXHaO4B/XLuUtmFANJqAA+8qkhqgabWic4himu3Ec7/2tgY/xxpgQ27BEEb/C86+NKYy87NofaHzeurDlT3dCJNV7yBN5Iz8OvlTKt2CF6XxC8Eb13CGTSH0QGsGhkUJFVAktemQ4w3V5q52j3cDHLrYP/aqNhYfwj0XpA50QQ1bts4CGHpEeJF8eIonEqnroWNIklpEtKmtNIPgkyKtZ6TFiVu4aDw0/mxu6fMb2vzL3z9Rd6GncqhnpwaHyr1n3s/He5eC70UsFk5AKNNa/TolKM0SjTJm/yX5eOwquphsqUp4LigxR13NpVPzGNONPVY8ZT9DwzEwWWhnfOI6NAf6pp4Xr9OapCGlwjH97+leBkq03/LXCOiS23JW8pRzsZMlGM76b9AOhgYgfPAWjKoK6OKqIvAfQkrl5B2Mi1txkXddewgPi9Z9umL4I37NobxRya9n7o/yxrBatt/1BBVE+4QBmHOU9NMgHvVUFOI0rPWy75zmSbOAqEh8Hebr8JrpgxcgwUqE7YRM4+kovUpjoRWLJqOd7wREIceEFyN
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-auth
      namespace: longhorn-system
