---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgCj1livi05JuLhrGzKOEN0Lxbi4slkD3gdL5LaM8pvgg6xpIsLBNqBsZAj5UChzqrZKKT/kVCelAp+QbkQ0A7zfxqhFGKtEncXxEqUk5ndMVWYe1o/P4hyVaIaToI1Kf3lEu1fEBni2Zydlt8cDqFFu7OfzuprBuo6GsICwGmxywRLHKcyT4I3Ig9TidwbSvwsYkRSzXSz1uRQFFZhT0eeD5qULsF+CW8TEenx53Zh9/UkAl6VOkapojuDVOBfmKgKYjrMdJJ7F4FKfJ1+jtJzsr9msyXv8fQ+RLCgQlO90zyBspbBGW5s4qKCv7K1VOWzOHns+VSE+H45HKtMFnYKC65n0WNRCfxeI9fYJ2pGEcpzzyJR0vscyCZlkIVIOSEiUcNjjS/UabnE5hKrTX2xk1lt/oyP+X2iMaSVAnwAvdznB94QULvllYW9JuM5jcSkWGciulKw02wKbwstDjklP2e+K2GXtxBVZC8WXnQw10F0c5Qoe0DNE6RaHIQLLyIgvQjyywCi73+P55opN9QrJN8aHtk49TO7ib2DouRrNb3KMvcz3+OoBkT0GjZtwAAkAMrHqvE/e2KFjZ0HQZovkBnk3lAxKr39NlMf2AaDfOD3nuozX1z8iz5jGBseeVSP9xeUo4UK9lQ3GoBGheyFJv9S6lBayYDGUibeOX/KtDhZY77cBUE0aRrMR8l1/aQFAPw9MCcFmsWQHiA==
    username: AgATQnR4+5KR83COjObC+8jX2WsklGQcU6U6KZrOyY3bOJJTpAHDbpCmSEcgi7Duorl3DC6uLL9jadgHIdTiNeFwh3ASS/g+lyDbQa9ZJSpffcRIEsuvRD7+KhvuivtT88Pf7CdXkroUG+KncnnMyDH3h5osa5E/qNXdKUPyCpAanjBh4vNUhz1R58JxzqbLbicVl2enPqJk2DqPOaN6sOaIE88Jro1Ivn2CuvbW8eiwmmhDyQOgLP3yiX3BsJG/HW8h96Yybof/EsRabeccP1NYbM2eYXNS1PyDy9y4iNk3GFK8s60j8KB7P/HipzqGglGkA8t+Q8E2A82ILYSef7C/jPsgPhEfo6b4RYHzdlLTehXQfT+f21ReSLZu5ujre/GI0KBvByT29vUdwZl/wboIoP4n34TtvAyxyxziALR0IRIjkuXD9+uTEyd/wZak2MEzvdVQpET2VK0/KuMF/4VcLOrtpVxXVFeD2Nwo6TBcTasQkoVxiOIM4NbdYj44OVpKFxFOyp/LnnxFxMf4MRBz+FNjtxC03wIUnA/hk+Vd1CEoHlNWvXcBWdJxUB2ILROv4hUG9qiavJatC4zgEyoYeRHYlcmqBC/tuWrVHN8V+0GjrQgQpWxdkAtn98talhwfqWl5JMtIN8PqhODwhec9rrj74sgihmCO6j/kLSKliroOkUKCoqY/9i7+Sy5AXld6YZfHkQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
