---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgAXJirlw0z63QnLfzc6lSY6sGK24xDktpP3smkLpBxigA79uJ+AvSTlrVTGKPQWfXGkpiq5EUKPzRTJAyMvi/wCEpkm/T6bMBNfOQdYddiMttma4EW7cHkYFIf4VJnnWiHgEEyB/GgZKtTcGxKnetFHV45ZS+McsHbt10a67SZLALp39NyXw1a8NWngvYKvu4xhkLmXb9w+O6mc8BInaxLuMnn5ASzdTRG8hlWHj2lXrySICWgvFx7aSW+AwUjh/ra2G0H/1/7sAMvsUSXXxZr6i2sHL5hzgSDOhtzhh3rsXH6Ft09bK+4y8YRg9dmzXFs7Y+BcaDfH4NIKMTdhg0KUJ7Dmgn4JHViAWZlPRrH4l6UbBUMxTXbPUzDS/fIEBFIJFk/pufQTJVNnxuIGa7RBGA8wcoM90NE/tzbRgnH43LN2iUsuUJcQKQMlmCo7QsW3gZgnrLHh3QUdF87n7/STJ43szEmh6dr1MmtC0xTWbgfBj3f8e0HmLcgnevyhKwQ9FPRHTyq/nhKRWGGNc/r2S5Wj3xEqhKrU+D5yBrOjt5gmdB7v1SnzMJ6raTvLMzNT1fQ0bzm+gDPY4L0WgMN0bShME6b//JeUPdpchc8pUxgrCxlPgGtjzGC8mgDFU2zjnbnaruMcWkm9cDpO8Qi5jS7c3jlEbY73guHtaPLQWJ3XTDHELQzI2E8Lyr9Bj9x/UTPgcKXDEfvOfoSyBX5bTn1wMIAw3+5DqcewU79MRusQB6WaRmee
    email: AgAzMEX6OtTDo+WuqUv9UOCn050zg/YeYCf+sly4oNHMstF2FDNjB0QDZ05t4/Jw+DoA0AmfOIAxmcDHJHkUe/lV7GRPxxtQ26XHMjYfTZEdVdFPSbgD+ZUoGl/g+NOIcR8rQ2q0s6QnionlU0B1hiSWGPItZgQn5kx9ZCNCRQEfMEUnMC9Let/KaATrDz9HZ5W9Sudhsol9aPMbQ8WJeikPSUfWNfOeZnPDy74I+rbkx4G6Q4Oa29CkNomSmLIfJVAC9YoEe0IVZii8GQytg6ZY9pD+f8zbpKeYLNYUj2aR90STUKNQRfLRdjAumunyo0Lt8nGG27mcDBsPA7B/WKJpBXSzkz+AlDLdS1MTBe6l6zWyO3tdltveUMYLCdK5uExR2mizRM66JPEjpCZrx4Swofbp3BGxJeClOjTAVvuhXve43aZ6O9xo0ctxE1b1o9XuzA2tnGWruRLkhxnQCifk03IdlVwsQDV1WZ1oNK7FzlYGd2vbovn/TEYH8+1dKevvwwimxMHMfh9qHXrZ4BD7BUXLQGxZbDHdOidswKuKC+yjZBTrV4Y7S2SPWR8F2+wx1mWPgxHBIrUbWSg6hH4BChPgxmmvcg2dj/2OR3RPi//Are2664m+EQSLzRqSVLztao55dSopKnBefn7Re+iHe3DEaiuozq6Av6+9W6CWbvBdZJ6M0zKQwMTs/micItL3TRtmeurYeN3YzqXK08JCaxxUaQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: traefik
