apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.atlasmalt.com`)
      kind: Rule
      middlewares:
        - name: longhorn-auth
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-tls  # ✅ Must match the Certificate resource secretName
