apiVersion: longhorn.io/v1beta1
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: s3://longhorn-backups@192.168.14.222:9900/longhorn?region=us-east-1&s3ForcePathStyle=true&endpoint=http://192.168.14.222:9900
  credentialSecret: minio-credentials
