apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-pvc
  namespace: trilium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeName: trilium-pv  # Bind explicitly to the static PV
