apiVersion: v1
kind: PersistentVolume
metadata:
  name: trilium-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: trilium-pv   # Must exactly match the restored volume’s name
