{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`{{ .Values.ingress.host }}`)"
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.port }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
