apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pvName | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  csi:
    driver: {{ .Values.persistence.csiDriver | quote }}
    volumeHandle: {{ .Values.persistence.pvName | quote }}
