{{- if .Values.persistence.createPVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvcName | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- if .Values.persistence.restore }}
  # When restoring, bind to an existing static volume.
  volumeName: {{ .Values.persistence.pvName | quote }}
  {{- end }}
{{- end }}
