{{- if .Values.grafana.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.grafana.certificate.name | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.grafana.certificate.secretName | quote }}
  issuerRef:
    name: {{ .Values.grafana.certificate.issuer.name | quote }}
    kind: {{ .Values.grafana.certificate.issuer.kind | quote }}
  dnsNames:
    {{- range .Values.grafana.certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
