apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie
  namespace: mealie
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mealie.atlasmalt.com`)
      kind: Rule
      services:
        - name: mealie
          port: 9000
  tls:
    secretName: mealie-tls  # ✅ Must match the Certificate resource secretName
