ingress:
  enabled: false  # Handled via IngressRoute

persistence:
  enabled: true
  size: 5Gi
  storageClassName: longhorn

admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        access: proxy

dashboardProviders:
  dashboard.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: "/var/lib/grafana/dashboards"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: "/var/lib/grafana/dashboards"

dashboards:
  default:
    kubernetes-overview:
      gnetId: 3146  # Built-in K8s Overview Dashboard
      revision: 1
      datasource: Prometheus

extraVolumeMounts:
  - name: dashboards
    mountPath: /var/lib/grafana/dashboards/
    readOnly: true

extraVolumes:
  - name: dashboards
    configMap:
      name: grafana-dashboards

grafana.ini:
  log:
    mode: console
    filters: "-live"
    level: info
  auth.basic:
    enabled: true
  auth.anonymous:
    enabled: false
  security:
    disable_brute_force_login_protection: false
    disable_login_form: false
  # live:
  #   enabled: false  # Disable Grafana Live
