additionalArguments:
  - "--entrypoints.websecure.http.middlewares=traefik-hsts@kubernetescrd"
  - "--entryPoints.ssh.address=:222"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  ssh:
    address: ":222"

expose:
  web:
    expose: true
  websecure:
    expose: true
  ssh:
    expose: true
    port: 222
    exposePort: 3222
    protocol: TCP
    entryPoint: ssh

env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-api-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-api-credentials

ingressRoute:
  dashboard:
    enabled: false

certIssuer: letsencrypt-prod

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

providers:
  kubernetesCRD: {}
  kubernetesIngress:
    publishedService:
      enabled: true
