apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-tls
  namespace: monitoring
spec:
  secretName: mealie-tls  # ✅ Cert-Manager will create this Secret automatically
  issuerRef:
    name: ${CERT_ISSUER}  # This will be replaced by the script
    kind: ClusterIssuer
  dnsNames:
    - mealie.atlasmalt.com  # ✅ This must match the domain in your IngressRoute
