apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trilium-tls
  namespace: trilium
spec:
  secretName: trilium-tls  # ✅ Cert-Manager will create this Secret automatically
  issuerRef:
    name: ${CERT_ISSUER}  # This will be replaced by the script
    kind: ClusterIssuer
  dnsNames:
    - trilium.atlasmalt.com  # ✅ This must match the domain in your IngressRoute
