replicaCount: 1

image:
  repository: triliumnext/notes
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: "trilium.example.com"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    secretName: "trilium-tls"
service:
  port: 8080

certificate:
  enabled: true
  name: trilium-tls
  secretName: trilium-tls
  issuer:
    name: "letsencrypt-staging"  # This value can be set via your CI/CD pipeline or .env file
    kind: ClusterIssuer
  dnsNames:
    - trilium.example.com

persistence:
  createPVC: true            # Always create the PVC via the chart
  restore: false             # Set this to true if you are restoring from backup
  pvcName: "trilium-pvc"
  pvName: "trilium-pv"       # Used for the static PV (restored volume)
  size: "5Gi"
  accessMode: "ReadWriteOnce"
  reclaimPolicy: "Retain"
  storageClassName: "longhorn"
  csiDriver: "driver.longhorn.io"
  numberOfReplicas: 3
  frontend: blockdev
  backupTargetName: default
  fromBackup: "s3://longhorn-backups@192.168.14.222:9900/longhorn?backup=backup-7a55f9cc125a40c9&volume=trilium-pv"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
